openai:
  - gpt-4o
  - gpt-4-turbo-preview
  - gpt-4
  - gpt-3.5-turbo

anthropic:
  - claude-3-opus-20240229
  - claude-3-sonnet-20240229
  - claude-3-haiku-20240307

groq:
  - llama3-8b-8192
  - llama3-70b-8192
  - mixtral-8x7b-32768

ollama:
  - llama2
  - llama3
  - mistral
  - mixtral
  - phi3
  - gemma

